### ISSUE TITLE
Can't use 'pip install python-i18n[YAML]'

### ISSUE THREAD

**Issue by eric0324** [tuvistavie/python-i18n#7]
I try to enter `pip install python-i18n[YAML]`

But it outputs an error message

`no matches found: python-i18n[YAML]`

why?

**Comment by tuvistavie** [comment]
I suppose you are using zsh.
You need to escape or quote `python-i18n[YAML]` or zsh will wrongly interpret it.

```
pip install "python-i18n[YAML]"
```

should work.

**Comment by eric0324** [comment]
Ok, I can use it!

thank you!
