### ISSUE TITLE
Can't use 'pip install python-i18n[YAML]'

### ISSUE THREAD

**Issue by eric0324** [tuvistavie/python-i18n#9]
I try to enter 

'''
pip install "python-i18n[YAML]"
'''

But it outputs some message

```
i18n-0.3.3-py3-none-any.whl
  Ignoring pyyaml: markers 'extra == "YAML"' don't match your environment
Installing collected packages: python-i18n
Successfully installed python-i18n-0.3.3
```

I want to Install `python-i18n[YAML]`.....

but it Install `python-i18n `...

why?

**Comment by tuvistavie** [comment]
Seems to be related to 
https://github.com/pypa/pip/issues/4617
I will change the extra require to lowercase.

**Comment by tuvistavie** [comment]
I just pushed a new version, hopefully

```
pip install 'python-i18n[yaml]'
```

should now work.
